#!/usr/bin/env python3

DATABASE_NAME = "test"

import argparse

from prettytable import PrettyTable
from pymongo import MongoClient, ASCENDING, TEXT

parser = argparse.ArgumentParser(description='Index pages.')
parser.add_argument('-a', '--add', nargs='+', help="[book] [page] [desc]")
parser.add_argument('-s', '--search', nargs='+')

args = parser.parse_args()

client = MongoClient()

db = client[DATABASE_NAME]

pg = db['book_pages']

pg.create_index([("book_title", ASCENDING), ("page_number", ASCENDING)], unique=True)
pg.create_index([('description', TEXT)], default_language='english')

if args.search:
    table = PrettyTable(['book', 'pg', 'desc'])
    for e in pg.find({'$text': {"$search": ' '.join(args.search)}}):
        table.add_row([e["book_title"], e["page_number"], e["description"]])
    print(table)
elif args.add:
    add_args = args.add
    pg.update_one(
        {
            "book_title": add_args[0],
            "page_number": add_args[1],
        }, {
            '$set': {"description": ' '.join(add_args[2:])}
        }, upsert=True)
